const declarations = {
    SETSELECTEDSERVER: "SETSELECTEDSERVER",
    SETSERVERS: "SETSERVERS",
    SETISLOADED: "SETISLOADED",
    SETCHANNELS: "SETCHANNELS",
    SETSELECTEDCHANNEL: "SETSELECTEDCHANNEL",
    SETMESSAGES: "SETMESSAGES",
}

export const {
    SETSELECTEDSERVER,
    SETSERVERS,
    SETISLOADED,
    SETCHANNELS,
    SETSELECTEDCHANNEL,
    SETMESSAGES,
} = declarations